### ISSUE TITLE
建议增加暂停按钮（或者检测硬盘还剩下低于3g就停止录像等功能） ，直接退出软件无法正确保存视频 ，还有保存视频的格式 比如ts mp4自由选择。

### ISSUE THREAD

**Issue by RainDrop13** [youxia2016/WinkTvLiveRecorderRelease#1]
不知道为什么这个软件录制的视频，标题都是标题注释都是 
微博:主播直播录播大师 直播录制客服QQ:960596621或1656395222 QQ交流群:812393257 直播录制客服QQ:960596621或1656395222 QQ交流群:812393257 微博:主播直播录播大师

**Comment by youxia2016** [comment]
会增加硬盘剩余空间检测，退出程序的时候会自动保存视频
