### ISSUE TITLE
系统防火墙 软件报毒是不是加料太多? 必须关闭系统自带防火墙才能运行!运行后 好像还限制录制主播及清晰度

### ISSUE THREAD

**Issue by Mikosxz** [youxia2016/WinkTvLiveRecorderRelease#3]
你这不是开源分享  你来这是为了卖软件啊 

[Imgur](https://imgur.com/Hnx5r5G)
[Imgur](https://imgur.com/F68SSDn)

**Comment by Mikosxz** [comment]
限制录制2个主播 绝了 .很久之前下载的版本 就不报毒 .不要加那么多料

**Comment by youxia2016** [comment]
软件做了加密处理,会被报毒,请放心使用，2个主播免费，超过2个需要付费，以维持开发经费。收费软件不会给你加料

**Comment by Mikosxz** [comment]
> 软件做了加密处理,会被报毒,请放心使用，2个主播免费，超过2个需要付费，以维持开发经费。收费软件不会给你加料

现在基本不安装杀毒软件  都是裸奔 连系统杀毒都过不了   估计也没几个人 敢用
